ISPP/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

from RoomBnB import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
]

urlpatterns += i18n_patterns(
    path('', views.base, name='base'),
    path('login/', auth_views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('tyc/', views.terms_and_conditions, name='tyc'),
    path('error/', views.not_allowed, name='error'),
    path('flats', views.list, name='flatList'),
    path('flats/', views.list, name='flatList'),
    path('flats/create',views.flatCreate, name='flatCreate'),
    path('room/rent/<int:room_id>', views.request_rent_room, name='requestRentRoom'),
    path('requests/list', views.requests_list, name='requestsList'),
    path('requests/accept/<int:request_id>/', views.accept_request, name='acceptRequest'),
    path('requests/deny/<int:request_id>/', views.deny_request, name='denyRequest'),
    path('flats/<int:flat_id>/', views.detail, name='flatDetail'),
    path('flats/keyword=<keyword>/elevator=<elevator>/washdisher=<washdisher>/balcony=<balcony>/window=<window>/air_conditioner=<air_conditioner>/', views.listWithProperties, name='flatListWithProperties'),
    path('flats/keyword=<keyword>', views.listWithKeyword, name='flatListWithKeyword'),
    path('profile/create',views.profileCreate, name='profileCreate'),
    path('profile/<int:user_id>/',views.showUserProperties, name='showUserProperties'),
    path('profile/edit', views.editUserProperties, name='editUserProperties'),
    path('flats/delete/<int:flat_id>/', views.flatDelete, name='flatDelete'),
    path('rooms/create/<int:flat_id>/', views.roomCreate, name='roomCreate'),
    path('rooms/<int:room_id>/', views.detailRoom, name='roomDetail'),
    path('roomReview/<int:room_id>/', views.roomReview, name='roomReview'),
    path('flatReview/<int:flat_id>/', views.flatReview, name='flatReview'),
    path('userReview/<int:flat_id>/<int:user_id>/', views.userReview, name='userReview'),
    path('writeRoomReview/<int:room_id>/', views.writeReviewRoom, name='writeRoomReview'),
    path('writeFlatReview/<int:flat_id>/', views.writeReviewFlat, name='writeFlatReview'),
    path('writeUserReview/<int:flat_id>/<int:user_id>/', views.writeReviewUser, name='writeUserReview'),
    path('rooms/request/<int:room_id>', views.request_rent_room, name='request_rent_room'),
    path('contracts/sign/<int:room_id>/', views.signContract, name='signContract'),
    path('payments', views.paymentList, name='paymentList'),
    path('flats/<int:flat_id>/editProperties', views.editFlatProperties, name='editFlatProperties'),
    path('rooms/<int:room_id>/editProperties', views.editRoomProperties, name='editRoomProperties'),
    # PAYPAL
    path(r'^paypal/', include('paypal.standard.ipn.urls')),
    path('rooms/<int:room_id>/payment', views.view_that_asks_for_money, name='payment'),
    path('paymentroom/<int:room_id>/paypal', views.paypal_response, name='paypal-response'),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RoomBnB/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(upload_to='profile/', default='profile/generic/default.png')


class UserProperties(models.Model):
    RATINGS = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    )

    DEGREES = (
        ('1', _('Nursing')),
        ('2', _('Computer Engineering')),
        ('3', _('Medicine')),
        ('4', _('Biology')),
        ('5', _('Architecture')),
    )

    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    smoker = models.BooleanField(_('Smoker'), default=False)
    pets = models.BooleanField(_('Pets'), default=False)
    sporty = models.CharField(_('Sporty'), max_length=1, choices=RATINGS)
    gamer = models.CharField(_('Gamer'), max_length=1, choices=RATINGS)
    sociable = models.CharField(_('Sociable'), max_length=1, choices=RATINGS)
    degree = models.CharField(_('Degree'), max_length=1, choices=DEGREES)


class Flat(models.Model):
    title = models.TextField(max_length=100)
    address = models.TextField(max_length=100)
    description = models.TextField(max_length=500)
    picture = models.ImageField(upload_to='flat/', default='flat/generic/default.jpg')
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='flats')


class FlatProperties(models.Model):
    flat = models.OneToOneField(Flat, on_delete=models.CASCADE)
    elevator = models.BooleanField(_('Elevator'), default=False)
    washdisher = models.BooleanField(_('Dishwasher'), default=False)


class Room(models.Model):
    description = models.TextField(max_length=500)
    price = models.FloatField()
    picture = models.ImageField(upload_to='room/', default='room/generic/default.jpg')
    temporal_owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)
    belong_to = models.ForeignKey(Flat, on_delete=models.CASCADE, related_name='rooms')


class RoomProperties(models.Model):
    BEDS = (
        ('1', _('Couple')),
        ('2', _('Single')),
        ('3', _('Sofa')),
        ('4', _('None')),
    )

    room = models.OneToOneField(Room, on_delete=models.CASCADE)
    balcony = models.BooleanField(_('Balcony'), default=False)
    window = models.BooleanField(_('Window'), default=False)
    air_conditioner = models.BooleanField(_('Air conditioner'), default=False)
    bed = models.CharField(_('Bed'), max_length=1, choices=BEDS, default=2)


class RentRequest(models.Model):
    requester = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rent_requests')
    creation_date = models.DateField(auto_now_add=True)
    requested = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='rent_requests')
    accepted = models.BooleanField(default=False)


class Contract(models.Model):
    text = models.TextField()
    date_signed = models.DateField(auto_now_add=True)
    landlord = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='landlord')
    tenant = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='tenant', null=True)
    room = models.ForeignKey(Room, on_delete=models.DO_NOTHING)


class Payment(models.Model):
    amount = models.FloatField()
    date = models.DateField(auto_now_add=True)
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE, default=None)


class Review(models.Model):
    RATINGS = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    )

    title = models.CharField(max_length=50)
    description = models.TextField(max_length=500, blank=True)
    date = models.DateField(auto_now_add=True)
    rating = models.CharField(max_length=1, choices=RATINGS)


class UserReview(Review):
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class FlatReview(Review):
    flat = models.ForeignKey(Flat, on_delete=models.CASCADE)


class RoomReview(Review):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)


class Image(models.Model):
    image = models.ImageField()


class FlatImage(Image):
    flat = models.ForeignKey(Flat, on_delete=models.CASCADE)


class RoomImage(Image):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)

templates/profile/create.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

    {% if user.is_authenticated %}

        <form class="pure-form pure-form-stacked" action="{% url 'profileCreate' %}" method="post" enctype="multipart/form-data">
            <fieldset>
                <legend>{% trans "Create a profile" %}</legend>
                {% csrf_token %}

                <!-- <p>
                    <label for="image">Image: </label>
                    <input id="id_image" type="file" class="" name="image">
                </p>
            -->

                {{ form.as_p }}
                <input class="pure-button pure-button-primary" type="submit" value="{% trans "Create" %}" />
            </fieldset>
        </form>

    {% else %}

        <h2>{% trans "You are not logged in." %}</h2>

    {% endif %}

{% endblock %}

templates/profile/detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Profile" %}{% endblock %}

{% block content %}

    <h1>{{ userProperties.profile.user.first_name }}</h1>

    <h2>{% trans "Details" %}</h2>

    <div class="pure-button-group" role="group">
        {% if userProperties.smoker == True %}
            <button class="pure-button">{% trans "Smoker" %}</button>
        {% else %}
            <button class="pure-button pure-button-disabled">{% trans "Smoker" %}</button>
        {% endif %}

        {% if userProperties.pets == True %}
            <button class="pure-button">{% trans "Pets" %}</button>
        {% else %}
            <button class="pure-button pure-button-disabled">{% trans "Pets" %}</button>
        {% endif %}

        <button class="pure-button">{% trans "Sporty" %}: {{ userProperties.sporty }}</button>
        <button class="pure-button">{% trans "Gamer" %}: {{ userProperties.gamer }}</button>
        <button class="pure-button">{% trans "Sociable" %}: {{ userProperties.sociable }}</button>
        <button class="pure-button">{% trans "Degree" %}: {{ userProperties.get_degree_display }}</button>

        <br><br>
    </div>

    {% if userProperties.profile.user == user %}
        <button class="pure-button pure-button-primary" onclick="location.href='{% url 'editUserProperties' %}'">{% trans "Edit profile" %}</button>
    {% endif %}

{% endblock %}

templates/profile/update.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Edit profile properties" %}{% endblock %}

{% block content %}

    <form class="pure-form pure-form-aligned" action="{% url 'editUserProperties' %}" method="post">
        <fieldset>
            <legend><h3>{% trans "Edit profile properties" %}</h3></legend>
            <br>
            {% csrf_token %}

            {{ form.profile.as_hidden }}

            <div class="pure-control-group">
                <label for="smoker">{% trans "Smoker" %}</label>
                {{ form.smoker }}
            </div>

            <div class="pure-control-group">
                <label for="pets">{% trans "Pets" %}</label>
                {{ form.pets }}
            </div>

            <div class="pure-control-group">
                <label for="sporty">{% trans "Sporty" %}</label>
                {{ form.sporty }}
            </div>

            <div class="pure-control-group">
                <label for="gamer">{% trans "Gamer" %}</label>
                {{ form.gamer }}
            </div>

            <div class="pure-control-group">
                <label for="sociable">{% trans "Sociable" %}</label>
                {{ form.sociable }}
            </div>

            <div class="pure-control-group">
                <label for="degree">{% trans "Degree" %}</label>
                {{ form.degree }}
            </div>

            <div class="pure-controls">
                <input class="pure-button pure-button-primary" type="submit" value="{% trans "Update" %}" />
            </div>

        </fieldset>
    </form>

{% endblock %}