ISPP/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

from RoomBnB import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
]

urlpatterns += i18n_patterns(
    path('', views.base, name='base'),
    path('login/', auth_views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('tyc/', views.terms_and_conditions, name='tyc'),
    path('error/', views.not_allowed, name='error'),
    path('flats', views.list, name='flatList'),
    path('flats/', views.list, name='flatList'),
    path('flats/create',views.flatCreate, name='flatCreate'),
    path('room/rent/<int:room_id>', views.request_rent_room, name='requestRentRoom'),
    path('requests/list', views.requests_list, name='requestsList'),
    path('requests/accept/<int:request_id>/', views.accept_request, name='acceptRequest'),
    path('requests/deny/<int:request_id>/', views.deny_request, name='denyRequest'),
    path('flats/<int:flat_id>/', views.detail, name='flatDetail'),
    path('flats/keyword=<keyword>/elevator=<elevator>/washdisher=<washdisher>/balcony=<balcony>/window=<window>/air_conditioner=<air_conditioner>/', views.listWithProperties, name='flatListWithProperties'),
    path('flats/keyword=<keyword>', views.listWithKeyword, name='flatListWithKeyword'),
    path('profile/create',views.profileCreate, name='profileCreate'),
    path('profile/<int:user_id>/',views.showUserProperties, name='showUserProperties'),
    path('profile/edit', views.editUserProperties, name='editUserProperties'),
    path('flats/delete/<int:flat_id>/', views.flatDelete, name='flatDelete'),
    path('rooms/create/<int:flat_id>/', views.roomCreate, name='roomCreate'),
    path('rooms/<int:room_id>/', views.detailRoom, name='roomDetail'),
    path('roomReview/<int:room_id>/', views.roomReview, name='roomReview'),
    path('flatReview/<int:flat_id>/', views.flatReview, name='flatReview'),
    path('userReview/<int:flat_id>/<int:user_id>/', views.userReview, name='userReview'),
    path('writeRoomReview/<int:room_id>/', views.writeReviewRoom, name='writeRoomReview'),
    path('writeFlatReview/<int:flat_id>/', views.writeReviewFlat, name='writeFlatReview'),
    path('writeUserReview/<int:flat_id>/<int:user_id>/', views.writeReviewUser, name='writeUserReview'),
    path('rooms/request/<int:room_id>', views.request_rent_room, name='request_rent_room'),
    path('contracts/sign/<int:room_id>/', views.signContract, name='signContract'),
    path('payments', views.paymentList, name='paymentList'),
    path('flats/<int:flat_id>/editProperties', views.editFlatProperties, name='editFlatProperties'),
    path('rooms/<int:room_id>/editProperties', views.editRoomProperties, name='editRoomProperties'),
    # PAYPAL
    path(r'^paypal/', include('paypal.standard.ipn.urls')),
    path('rooms/<int:room_id>/payment', views.view_that_asks_for_money, name='payment'),
    path('paymentroom/<int:room_id>/paypal', views.paypal_response, name='paypal-response'),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RoomBnB/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(upload_to='profile/', default='profile/generic/default.png')


class UserProperties(models.Model):
    RATINGS = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    )

    DEGREES = (
        ('1', _('Nursing')),
        ('2', _('Computer Engineering')),
        ('3', _('Medicine')),
        ('4', _('Biology')),
        ('5', _('Architecture')),
    )

    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    smoker = models.BooleanField(_('Smoker'), default=False)
    pets = models.BooleanField(_('Pets'), default=False)
    sporty = models.CharField(_('Sporty'), max_length=1, choices=RATINGS)
    gamer = models.CharField(_('Gamer'), max_length=1, choices=RATINGS)
    sociable = models.CharField(_('Sociable'), max_length=1, choices=RATINGS)
    degree = models.CharField(_('Degree'), max_length=1, choices=DEGREES)


class Flat(models.Model):
    title = models.TextField(max_length=100)
    address = models.TextField(max_length=100)
    description = models.TextField(max_length=500)
    picture = models.ImageField(upload_to='flat/', default='flat/generic/default.jpg')
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='flats')


class FlatProperties(models.Model):
    flat = models.OneToOneField(Flat, on_delete=models.CASCADE)
    elevator = models.BooleanField(_('Elevator'), default=False)
    washdisher = models.BooleanField(_('Dishwasher'), default=False)


class Room(models.Model):
    description = models.TextField(max_length=500)
    price = models.FloatField()
    picture = models.ImageField(upload_to='room/', default='room/generic/default.jpg')
    temporal_owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)
    belong_to = models.ForeignKey(Flat, on_delete=models.CASCADE, related_name='rooms')


class RoomProperties(models.Model):
    BEDS = (
        ('1', _('Couple')),
        ('2', _('Single')),
        ('3', _('Sofa')),
        ('4', _('None')),
    )

    room = models.OneToOneField(Room, on_delete=models.CASCADE)
    balcony = models.BooleanField(_('Balcony'), default=False)
    window = models.BooleanField(_('Window'), default=False)
    air_conditioner = models.BooleanField(_('Air conditioner'), default=False)
    bed = models.CharField(_('Bed'), max_length=1, choices=BEDS, default=2)


class RentRequest(models.Model):
    requester = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rent_requests')
    creation_date = models.DateField(auto_now_add=True)
    requested = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='rent_requests')
    accepted = models.BooleanField(default=False)


class Contract(models.Model):
    text = models.TextField()
    date_signed = models.DateField(auto_now_add=True)
    landlord = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='landlord')
    tenant = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='tenant', null=True)
    room = models.ForeignKey(Room, on_delete=models.DO_NOTHING)


class Payment(models.Model):
    amount = models.FloatField()
    date = models.DateField(auto_now_add=True)
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE, default=None)


class Review(models.Model):
    RATINGS = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    )

    title = models.CharField(max_length=50)
    description = models.TextField(max_length=500, blank=True)
    date = models.DateField(auto_now_add=True)
    rating = models.CharField(max_length=1, choices=RATINGS)


class UserReview(Review):
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class FlatReview(Review):
    flat = models.ForeignKey(Flat, on_delete=models.CASCADE)


class RoomReview(Review):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)


class Image(models.Model):
    image = models.ImageField()


class FlatImage(Image):
    flat = models.ForeignKey(Flat, on_delete=models.CASCADE)


class RoomImage(Image):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)

templates/room/create.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Create a room" %}{% endblock %}

{% block content %}

    <form class="pure-form pure-form-aligned" action="{% url 'roomCreate' flatid %}" method="post" enctype="multipart/form-data">
        <fieldset>
            <legend><h3>{% trans "Create a room" %}</h3></legend>
            <br>
            {% csrf_token %}

            <div class="pure-control-group">
                <label for="price">{% trans "Price" %}</label>
                {{ form.price }}
                <span class="pure-form-message-inline">{% trans "Required" %}</span>
            </div>

            <div class="pure-control-group">
                <label for="description">{% trans "Description" %}</label>
                {{ form.description }}
                <span class="pure-form-message-inline">{% trans "Required" %}</span>
            </div>

            <div class="pure-control-group">
                <label for="picture">{% trans "Picture" %}</label>
                {{ form.picture }}
                <span class="pure-form-message-inline">{% trans "Required" %}</span>
            </div>

            <div class="pure-controls">
                <input class="pure-button pure-button-primary" type="submit" value="{% trans "Create" %}" />
            </div>
        </fieldset>
    </form>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% endblock %}

templates/room/detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Flat reviews" %}{% endblock %}

{% block content %}

    <h1>{{ room.description }}</h1>

    <section class="listings">
        <div class="wrapper">
             <ul class="properties_list">
                 <li>
                     <img src="{{ room.picture.url }}" alt="" title="" class="property_img"/>
                     <span class="price">{{ room.price }} €</span>
                 </li>
             </ul>
        </div>
    </section>

    <h2>{% trans "Details" %}</h2>

    <div class="pure-button-group" role="group">
        {% if roomDetails.balcony == True %}
            <button class="pure-button">{% trans "Balcony" %}</button>
        {% else %}
            <button class="pure-button pure-button-disabled">{% trans "Balcony" %}</button>
        {% endif %}

        {% if roomDetails.window == True %}
            <button class="pure-button">{% trans "Window" %}</button>
        {% else %}
            <button class="pure-button pure-button-disabled">{% trans "Window" %}</button>
        {% endif %}

        {% if roomDetails.air_conditioner == True %}
            <button class="pure-button">{% trans "Air conditioner" %}</button>
        {% else %}
            <button class="pure-button pure-button-disabled">{% trans "Air conditioner" %}</button>
        {% endif %}

        <button class="pure-button">{% trans "Bed" %}: {{ roomDetails.get_bed_display }}</button>

        <br><br>
    </div>

    {% if room.temporal_owner %}

        <table class="pure-table">

        <tr style="background: rgba(149, 186, 223, 1); border: 1px solid rgba(200, 100, 0, 0.3);">

            <th colspan="5">{% trans "Tenant" %}</th>

        </tr>

        <tr>

            <th colspan="2">{% trans "Personal information" %}</th>

            <th colspan="2">{% trans "Details" %}</th>

        </tr>

        <tr style="background: rgba(149, 186, 223, 1); border: 1px solid rgba(200, 100, 0, 0.3);">

            <td><b>{% trans "User" %}</b></td>

            <td><button class="pure-button pure-button-primary" onclick="location.href='{% url 'showUserProperties' userProperties.profile.user.id %}'">{{ userProperties.profile.user.username }}</button></td>

            <td><b>{% trans "Smoker" %}</b></td>

            <td align="center">
                {% if userProperties.smoker == True %}
                    &#10004;
                {% else %}
                    &#10005;
                {% endif %}
            </td>

        </tr>

        <tr>

            <td><b>{% trans "Name" %}</b></td>

            <td>{{ userProperties.profile.user.first_name }}</td>

            <td><b>{% trans "Pets" %}</b></td>

            <td align="center">
                {% if userProperties.pets == True %}
                    &#10004;
                {% else %}
                    &#10005;
                {% endif %}
            </td>

        </tr>
        <tr style="background: rgba(149, 186, 223, 1); border: 1px solid rgba(200, 100, 0, 0.3);">

            <td><b>{% trans "Image" %}</b></td>

            <td><img src="https://ui-avatars.com/api/?name={{ userProperties.profile.user.username }}&size=50&rounded=true&background=fff3e0" width="50" height="50"></td>

            <td><b>{% trans "Sporty" %}</b></td>

            <td align="center">
               {{ userProperties.sporty }}
            </td>

        </tr>
        <tr>

            <td colspan="2" rowspan="3"></td>

            <td><b>{% trans "Gamer" %}</b></td>

            <td align="center">
               {{ userProperties.gamer }}
            </td>

        </tr>
        <tr style="background: rgba(149, 186, 223, 1); border: 1px solid rgba(200, 100, 0, 0.3);">

            <td><b>{% trans "Sociable" %}</b></td>

            <td align="center">
                {{ userProperties.sociable }}
            </td>

        </tr>
        <tr>

            <td><b>{% trans "Degree" %}</b></td>

            <td align="center">
               {{ userProperties.get_degree_display }}
            </td>

        </tr>

        </table>
    {% endif %}
    <br><br>

    <button class="pure-button pure-button-primary" onclick="location.href='{% url 'roomReview' room.id %}'">{% trans "Room reviews" %}</button>

    {% if room.belong_to.owner.user == user %}
        <button class="pure-button" onclick="location.href='{% url 'editRoomProperties' room.id %}'">{% trans "Update properties" %}</button>
    {% endif %}

    {% if room.temporal_owner == user %}
        <button class="pure-button pure-button-primary" onclick="location.href='{% url 'payment'  room.id %}'">{% trans "Make payment" %}</button>
    {% endif %}

{% endblock %}

templates/room/review.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Room reviews" %}{% endblock %}

{% block content %}

    <table class="pure-table">
        <thead>
            <tr>
                <th>{% trans "Title" %}</th>
                <th>{% trans "Date" %}</th>
                <th>{% trans "Description" %}</th>
                <th>{% trans "Rating" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for review in roomRev %}
            <tr>
                <th>{{ review.title }}</th>
                <th>{{ review.date }}</th>
                <th>{{ review.description }}</th>
                <th>{{ review.rating }}</th>
            </tr>
        </tbody>
        {% endfor %}
    </table>
    <br>

    {% if user == room.temporal_owner %}
        <button class="pure-button pure-button-primary" onclick="location.href='{% url 'writeRoomReview' room.id %}'">{% trans "Write a review" %}</button>
    {% endif %}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% endblock %}

templates/room/updateProperties.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Edit room properties" %}{% endblock %}

{% block content %}

    {% if user.is_authenticated %}

        <form class="pure-form pure-form-aligned" action="{% url 'editRoomProperties' room_id %}" method="post">
            <fieldset>
                <legend><h3>{% trans "Edit room properties" %}</h3></legend>
                <br>
                {% csrf_token %}

                {{ form.room.as_hidden }}

                <div class="pure-control-group">
                    <label for="balcony">{% trans "Balcony" %}</label>
                    {{ form.balcony }}
                </div>

                <div class="pure-control-group">
                    <label for="window">{% trans "Window" %}</label>
                    {{ form.window }}
                </div>

                <div class="pure-control-group">
                    <label for="air_conditioner">{% trans "Air conditioner" %}</label>
                    {{ form.air_conditioner }}
                </div>

                <div class="pure-control-group">
                    <label for="bed">{% trans "Bed" %}</label>
                    {{ form.bed }}
                </div>

                <div class="pure-controls">
                    <input class="pure-button pure-button-primary" type="submit" value="{% trans "Update" %}" />
                </div>

            </fieldset>
        </form>

     {% else %}

        <h2>{% trans "You are not logged in." %}</h2>

    {% endif %}

{% endblock %}

templates/room/writeReview.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Write a room review" %}{% endblock %}

{% block content %}

    {% if user.is_authenticated %}

        <form class="pure-form pure-form-aligned" action="{% url 'writeRoomReview' roomid %}" method="post">
            <fieldset>
                <legend><h3>{% trans "Create a review" %}</h3></legend>
                <br>
                {% csrf_token %}

                <div class="pure-controls">
                    <label for="title">{% trans "Title" %}: </label>
                    {{ form.title }}
                    <span class="pure-form-message-inline">{% trans "Required" %}</span>
                </div>

                <div class="pure-controls">
                    <label for="description">{% trans "Description" %}: </label>
                    {{ form.description }}
                    <span class="pure-form-message-inline">{% trans "Required" %}</span>
                </div>

                <div class="pure-controls">
                    <label for="rating">{% trans "Rating" %}:</label>
                    <select name="rating">
                       <option value="1" selected="selected">1</option>
                       <option value="2">2</option>
                       <option value="3">3</option>
                       <option value="4">4</option>
                       <option value="5">5</option>
                    </select>
                    <span class="pure-form-message-inline">{% trans "Required" %}</span>
                </div>

                <div class="pure-controls">
                    <input class="pure-button pure-button-primary" type="submit" value="{% trans "Create" %}" />
                </div>
            </fieldset>
        </form>

    {% else %}

        <h2>{% trans "You are not logged in." %}</h2>

    {% endif %}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% endblock %}